---
- name: Execute deployment script
  hosts: Slave
  become: yes

  tasks:
    - name: Copy deployment script
      copy:
        src: ./deploy.sh
        dest: /tmp/deploy.sh
        mode: 0755

    - name: Execute deployment script
      shell: /tmp/deploy.sh >> /vagrant/ansible.log 2>&1

    - name: Ensure correct permissions for /vagrant directory
      file:
        path: /vagrant
        state: directory
        mode: 0755
      when: not ansible_check_mode

    - name: Ensure correct permissions for uptime.log file
      file:
        path: /vagrant/uptime.log
        state: touch
        mode: 0644
      when: not ansible_check_mode

    - name: Create a cron job to check the server's uptime every 12 am
      cron:
        name: "Check server uptime"
        minute: "0"
        hour: "0"
        job: "uptime >> /vagrant/uptime.log"
        user: vagrant